#!/bin/bash

parseInputDate() {
    # Used to check which machine we are running on
    local unameOut="$(uname -s)"
    local MAC_OS="Darwin"
    local LINUX_OS="Linux"

    local defaultDateFormat="%Y-%m-%d"

    local dateToParse="${1}"
    # Validate input date and format it
    # Take into account different implementations of `date` command
    if [ "${unameOut}" = "${LINUX_OS}" ]
    then
        local requiredDate="${dateToParse:-today}"
        echo "$( date -d "${requiredDate}" +${defaultDateFormat})"
        return 0
    elif [ "${unameOut}" = "${MAC_OS}" ]
    then
        # On BSD based systems (i.e. Mac), date cannot accept any input as a string
        # So we have to enforce a specific format to validate against
        local todaysDateMacOs="$(date -j +${defaultDateFormat})"
        local requiredDate="${dateToParse:-${todaysDateMacOs}}"

        echo "$(date -j -f "${defaultDateFormat}" "${requiredDate}" > /dev/null 2>&1)"

        # $? Will contain the return code of the last command
        if [ "$?" = "1" ]
        then
            echo "Invalid date format ! Received: \"${requiredDate}\". Date should match: ${defaultDateFormat}"
            exit 1
        fi
        # A bit more context on -f -> "-f input_fmt new_date +output_fmt"
        # @see `man date` on BSD/Mac OS for more details
        echo "$(date -j -f "${defaultDateFormat}" ${requiredDate} +${defaultDateFormat})"
        return 0
    fi
    echo "Unsupported platform '${unameOut}'"
    return 1
}

# Expected argument, one of "today" | "tomorrow" | "yesterday"
# Based on the underlying OS, use the correct implementation of `date`
generateDate() {
    # Used to check which machine we are running on
    local unameOut="$(uname -s)"
    local MAC_OS="Darwin"
    local LINUX_OS="Linux"

    local defaultDateFormat="%Y-%m-%d"

    local requestedDate="${1}"
    local generatedDate=""
    if [ "${unameOut}" = "${MAC_OS}" ]
    then
        case "${requestedDate}" in
        "tomorrow")
            generatedDate="$(date -j -v+1d +${defaultDateFormat})"
            ;;

        "yesterday")
            generatedDate="$(date -j -v-1d +${defaultDateFormat})"
            ;;

        *)
            generatedDate="$(date -j +${defaultDateFormat})"
            ;;
        esac
    elif [ "${unameOut}" = "${LINUX_OS}" ]
    then
        generatedDate="$( date --date="${requestedDate}" +${defaultDateFormat} )"
    fi
    echo "${generatedDate}"
}


