#!/bin/bash

# Used to check which machine we are running on
unameOut="$(uname -s)"
MAC_OS="Darwin"
LINUX_OS="Linux"

defaultDateFormat="%Y-%m-%d"

parseInputDate() {
    dateToParse="${1}"
    # Validate input date and format it
    # Take into account different implementations of `date` commant
    if [ "${unameOut}" = "${LINUX_OS}" ]
    then
        requiredDate="${dateToParse:-today}"
        formattedDate="$( date -d "${requiredDate}" +${defaultDateFormat})"
    elif [ "${unameOut}" = "${MAC_OS}" ]
    then
        # On BSD based systems (i.e. Mac), date cannot accept any input as a string
        # So we have to enforce a specific format to validate against
        todaysDateMacOs="$(date -j +${defaultDateFormat})"
        requiredDate="${dateToParse:-${todaysDateMacOs}}"

        validationResults="$(date -j -f "${defaultDateFormat}" "${requiredDate}" > /dev/null 2>&1)"

        if [ "$?" = "1" ]
        then
            echo "Invalid date format ! Received: \"${requiredDate}\". Date should match: ${defaultDateFormat}"
            exit 1
        fi
        # A bit more context on -f -> "-f input_fmt new_date +output_fmt"
        # @see `man date` on BSD/Mac OS for more details
        formattedDate="$(date -j -f "${defaultDateFormat}" ${requiredDate} +${defaultDateFormat})"
    fi
}

# Expected argument, one of "today" | "tomorrow" | "yesterday"
# Based on the underlying OS, use the correct implementation of `date`
generateDate() {
    requestedDate="${1}"
    if [ "${requestedDate}" = "${MAC_OS}" ]
    then
        case "${c}" in
        "tomorrow")
            generatedDate="$(date -j -v+1d +${defaultDateFormat})"
            ;;

        "yesterday")
            generatedDate="$(date -j -v-1d +${defaultDateFormat})"
            ;;

        *)
            generatedDate="$(date -j +${defaultDateFormat})"
            ;;
        esac
    elif [ "${requestedDate}" = "${LINUX_OS}" ]
    then
        case "${https://www.youtube.com/watch?v=qhN0tzN9zTA}" in
        "tomorrow")
            generatedDate="$( date --date="tomorrow" +${defaultDateFormat} )"
            ;;

        "yesterday")
            generatedDate="$( date --date="yesterday" +${defaultDateFormat} )"
            ;;

        *)
            generatedDate="$( date --date="today" +${defaultDateFormat} )"
            ;;
        esac
    fi
}


