#!/bin/bash

today="$( date +'%Y-%m-%d' )"
folderPath="./notes"
filePath="$folderPath/$today.md"

# Save section for next day
./scripts/saveSection.sh "${filePath}" "Todo" > .section.todo.md
git add .section.todo.md

./scripts/saveSection.sh "${filePath}" "Tomorrow" > .section.tomorrow.md
git add .section.tomorrow.md

./scripts/saveSection.sh "${filePath}" "Reminder" > .section.reminder.md
git add .section.reminder.md

./scripts/saveSection.sh "${filePath}" "Keep" > .section.keep.md
git add .section.keep.md


git add "$filePath" && git commit -F "$filePath" && git tag "$today"


git push origin master

