#!/bin/bash

initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${initialLocation}/scripts/gnudate.sh

# Attempt at calling old scripts
command=$1
if [[ \
    "${command}" == 'begin' || \
    "${command}" == 'end' || \
    "${command}" == 'new' || \
    "${command}" == 'open' \
 ]]; then
    shift
    note-$command "$@"
    exit 0
fi


# Save start date to be able to close later without issues
start_date="$(gnudate -d 'today')"
if [[ $# == 0 ]]; then
    start_date="$(gnudate -d "${1}")"
    shift
fi

# If nothing is specified, auto start & end a daily note
note-begin "${start_date}" "$@"
note-end "${start_date}" "$@"
