#!/bin/bash

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${rootFolder}/date-parser"

# generateDate (function) is sourced from date-parser
generatedDate="$(generateDate $1)"
documentDate="${1:-${generatedDate}}"

. "${rootFolder}/note-sync"

. "${rootFolder}/note-open" "${documentDate}"
