#!/bin/bash

source ./date-parser "yesterday"

initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# generateDate (function) and generatedDate (variable) are sourced from date-parser
generateDate
document_date="${1:-${generatedDate}}"

. "${initialLocation}/note-sync"

. "${initialLocation}/note-open" "${document_date}"
