#!/bin/bash

initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${initialLocation}/date-parser"

. ${initialLocation}/note-sync

# generateDate (function) and generatedDate (variable) are sourced from date-parser
generateDate $1
document_date="${1:-${generatedDate}}"

. ${initialLocation}/note-new "${document_date}"
