#!/bin/bash

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
notesFolder="$( cat "${rootFolder}/.noteFolderPath")"

if [ -z $notesFolder ]; then
  echo "Can't find root folder '${notesFolder}', did you run note-setup?"
  exit 1
fi

noteFolderLocation="${notesFolder}/notes"

# parseInputDate (function) and formattedDate (variable) are sourced from date-parser
source "${rootFolder}/date-parser"
parseInputDate $1
filePath="${noteFolderLocation}/${formattedDate}.md"

if [ ! -e $filePath	]
then
    # Create today's file based on template
    cp "${rootFolder}/.template.md" "${filePath}"

    echo "Applying sections to ${filePath}:"
    for section in $(ls -a "${rootFolder}" | grep .section.); do
      echo "* ${section}"
      cat "${rootFolder}/${section}" >> "${filePath}"
      rm "${rootFolder}/${section}"
    done
fi

echo "Editing file ${filePath}"
$EDITOR "${filePath}"

