#!/bin/bash

echo "note open command: '$0 $@'"
required_date="${1:-today}"

initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${initialLocation}/scripts/gnudate.sh
rootFolder="$( cat "${initialLocation}/.noteFolderPath")"
if [ -z $rootFolder ]; then
  echo "Can't find root folder, did you run note-setup?"
  exit 1
fi

formated_date="$( gnudate -d "${required_date}" +'%Y-%m-%d' )"
noteFolderLocation="${rootFolder}/journal"

filePath="${noteFolderLocation}/${formated_date}.md"


if [ ! -d "${noteFolderLocation}"	]
then
	mkdir -p "${noteFolderLocation}"
fi


if [ ! -e $filePath	]
then
    echo "No file to open @ ${filePath}"
else

    echo "Editing file ${filePath}"
    ${EDITOR} "${filePath}"
fi


