#!/bin/bash

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
notesFolder="$( cat "${rootFolder}/.noteFolderPath")"
if [ ! -z "${notesFolder}" ]; then
    echo "${notesFolder}"
fi

