#!/bin/bash

initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
notesFolderPath="$( cat "${initialLocation}/.noteFolderPath")"
if [ -z $notesFolderPath ]; then
  echo "Can't find root folder ${notesFolderPath}'', did you run note-setup?"
  exit 1
fi

cd "${notesFolderPath}"
git fetch origin && git rebase origin/master
cd "${initialLocation}"
