#!/bin/bash

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
noteFolder="${1}"
gitRemoteUrl="${2}"

if [[ $noteFolder = 'update' ]]; then
  noteFolder=$(cat "${rootFolder}/.noteFolderPath")
  gitRemoteUrl=$(cd "${noteFolder}" && git remote -v | tail -n 1 | awk '{print $2}')
  pushd "${rootFolder}"
  git fetch origin && git rebase origin/master
  gitStatusCode=$?
  if [[ $gitStatusCode != 0 ]]; then
    echo "Was not able to update, go to '${rootFolder}' and fix previously mentionned issues"
    exit $gitStatusCode
  fi
  popd
fi

if [ -z $noteFolder ]; then
  echo "Please provide a path to your note folder"
  echo "ex: ./note-setup /my-daily-notes my-server.com/daily-notes.git"
  exit 1
fi

if [ -z $gitRemoteUrl ]; then
  echo "Please provide an url to your git repository"
  echo "ex: ./note-setup /my-daily-notes my-server.com/daily-notes.git"
  exit 1
fi

echo ' ___________________________________________________________ '
echo '/     ____        _ __            _   __      __            \'
echo '|    / __ \____ _(_) /_  __      / | / /___  / /____  _____ |'
echo '|   / / / / __ `/ / / / / /_____/  |/ / __ \/ __/ _ \/ ___/ |'
echo '|  / /_/ / /_/ / / / /_/ /_____/ /|  / /_/ / /_/  __(__  )  |'
echo '| /_____/\__,_/_/_/\__, /     /_/ |_/\____/\__/\___/____/   |'
echo '|                 /____/                                    |'
echo '\___________________________________________________________/'
echo ''

if [[ ! "${noteFolder}" = /* ]];
then
  echo "Path '${noteFolder}' is not absolute"
  exit 1
fi

if [ ! -d "${noteFolder}"	]
then
  echo "Folder '${noteFolder}' does not exist"
  exit 1
fi

# Save note folder location
echo "Note folder is '${noteFolder}'"
echo "${noteFolder}" > "${rootFolder}/.noteFolderPath"

# Copy base sections file
cp "${rootFolder}/.sections" "${noteFolder}/.sections"

# Copy base template file
cp "${rootFolder}/.template.md" "${noteFolder}/.template.md"

echo 'Setup completed!'
echo ''
echo "Add this to your .bashrc &/or .zshrc 'export PATH=\"\${PATH}:${rootFolder}\"'"
