#!/bin/bash

initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

document_date="$( date --date="yesterday" +'%Y-%m-%d' )"

. "${initialLocation}/note-sync"

. "${initialLocation}/note-open" "${document_date}"
