#!/bin/bash

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${rootFolder}/date-parser"

# generateDate (function) and generatedDate (variable) are sourced from date-parser
generateDate "tomorrow"
document_date="${1:-${generatedDate}}"

. "${rootFolder}/note-sync"

. "${rootFolder}/note-open" "${document_date}"
