#!/bin/bash

required_date="${1:-today}"

initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source ${initialLocation}/scripts/gnudate.sh
rootFolder="$(cat "${initialLocation}/.noteFolderPath")"
if [ -z $rootFolder ]; then
  echo "Can't find root folder, did you run note-setup?"
  exit 1
fi

formated_date="$( gnudate -d "${required_date}" +'%Y-%m-%d' )"
noteFolderLocation="${rootFolder}/journal"
filePath="${noteFolderLocation}/${formated_date}.md"


cd "${rootFolder}"

sections=$(cat "${rootFolder}/.sections")

if [[ ! -z $sections ]]; then
  for section in $sections; do
    # Save section for next day
    "${initialLocation}/scripts/saveSection.sh" "${filePath}" "${section}" > ".section.${section}.md"
    git add ".section.${section}.md"
  done
fi

git add "${filePath}" && git commit -F "${filePath}" && git tag "${formated_date}"


git push origin master

cd "${initialLocation}"
