#!/bin/bash

initialLocation="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
rootFolder="$(cat "${initialLocation}/.noteFolderPath")"
if [ -z $rootFolder ]; then
  echo "Can't find root folder, did you run note-setup?"
  exit 1
fi

# parseInputDate (function) and formattedDate (variable) are sourced from date-parser
source "${rootFolder}/date-parser" $1
parseInputDate

noteFolderLocation="${rootFolder}/notes"
filePath="${noteFolderLocation}/${formattedDate}.md"

cd "${rootFolder}"

sections=$(cat "${rootFolder}/.sections")

if [[ ! -z $sections ]]; then
  for section in $sections; do
    # Save section for next day
    . "${initialLocation}/scripts/saveSection.sh" "${filePath}" "${section}" > ".section.${section}.md"
    git add ".section.${section}.md"
  done
fi

git add "${filePath}" && git commit -F "${filePath}" && git tag "${formattedDate}"


git push origin master

cd "${initialLocation}"
