#!/bin/bash

required_date="${1:-today}"

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
rootFolder="$( cat "${rootFolder}/.noteFolderPath")"
if [ ! -z $rootFolder ]; then
  echo "Can't find root folder, did you run note-setup?"
  exit 1
fi

formated_date="$( date -d "${required_date}" +'%Y-%m-%d' )"
folderPath="${rootFolder}/notes"

filePath="${folderPath}/${formated_date}.md"


if [ ! -d "${folderPath}"	]
then
	mkdir -p "${folderPath}"
fi


if [ ! -e $filePath	]
then
    echo "No file to open @ ${filePath}"
else

    echo "Editing file ${filePath}"
    $EDITOR "${filePath}"
fi


