#!/bin/bash

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
notesFolder="$( cat "${rootFolder}/.noteFolderPath")"
if [ -z $notesFolder ]; then
  echo "Can't find root folder ${notesFolder}'', did you run note-setup?"
  exit 1
fi

cd "${notesFolder}"
git fetch origin && git rebase origin/master
cd "${rootFolder}"
