#!/bin/bash

source ./date-parser $1

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
rootFolder="$( cat "${rootFolder}/.noteFolderPath")"

if [ -z $rootFolder ]; then
  echo "Can't find root folder '${rootFolder}', did you run note-setup?"
  exit 1
fi

noteFolderLocation="${rootFolder}/notes"
# parseInputDate (function) and formattedDate (variable) are sourced from date-parser
parseInputDate
filePath="${noteFolderLocation}/${formattedDate}.md"

if [ ! -d "${noteFolderLocation}"	]
then
	mkdir -p "${noteFolderLocation}"
fi

if [ ! -e $filePath	]
then
    # Create today's file based on template
    cp "${rootFolder}/.template.md" "${filePath}"

    echo "Applying sections to ${filePath}:"
    for section in $(ls -a "${rootFolder}" | grep .section.); do
      echo "* ${section}"
      cat "${rootFolder}/${section}" >> "${filePath}"
      rm "${rootFolder}/${section}"
    done
fi


echo "Editing file ${filePath}"
$EDITOR "${filePath}"

