#!/bin/bash

rootFolder="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
rootFolder="$( cat "${rootFolder}/.noteFolderPath")"
if [ -z $rootFolder ]; then
  echo "Can't find root folder, did you run note-setup?"
  exit 1
fi

# parseInputDate (function) and formattedDate (variable) are sourced from date-parser
source "${rootFolder}/date-parser" $1
parseInputDate
noteFolderLocation="${rootFolder}/notes"
filePath="${noteFolderLocation}/${formattedDate}.md"

if [ ! -d "${noteFolderLocation}"	]
then
	mkdir -p "${noteFolderLocation}"
fi

if [ ! -e $filePath	]
then
    echo "No file to open @ ${filePath}"
else

    echo "Editing file ${filePath}"
    $EDITOR "${filePath}"
fi


