#!/bin/bash

# this line registers our custom autocompletion function to be invoked
# when completing arguments to the repo command

# Only works in bash, using this in zsh will not work with partial words (`note aaa bb<Tab>` doesn't work)
_note_bashcomplete() {
    rootFolder="$(note-folder)"

    local target
    local file

    target=""
    arg_count=0
    while (( $arg_count < ${#COMP_WORDS[@]}-1 )) #-1 to remove cmd name
    do
        target="/${COMP_WORDS[COMP_CWORD-arg_count]}$target"
        ((arg_count++))
    done
    target="$rootFolder/notes$target"

    if [[ -d $target ]]; then
        for file in $(ls $target); do
            if [[ -f $target/$file ]]; then
                COMPREPLY+=( $(basename "$file" | cut -f 1 -d '.') )
            else
                COMPREPLY+=( $(basename "$file") )
            fi
        done
    else
        for file in $target*; do
            if [[ -f $file ]]; then
                COMPREPLY+=( $(basename "$file" | cut -f 1 -d '.') )
            else
                COMPREPLY+=( $(basename "$file") )
            fi
        done
    fi
}

complete -F _note_bashcomplete note
