#!/bin/bash

note_type="wiki"
note_category="${1}"
note_sub_category="${2}"
note_name="${3}"

echo "$note_name"
echo "==="
echo ": Quick TLDR"
echo ""
echo "---"
echo "* [Header](#header)"
echo "---"
echo "# Header {#header}"
echo "Content here"
